<a href="https://colab.research.google.com/github/inki53/python-deep-learning/blob/master/Copia_de_03_Capitulo_redes_neuronales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
x=np.array([[1,2,3,4,5,6]],dtype=np.int8)

print(x)
print(x,x.shape,sep='\n')

[[1 2 3 4 5 6]]
[[1 2 3 4 5 6]]
(1, 6)


In [ ]:
y=np.reshape(x,(2,3))
print(y)

In [ ]:
z=np.reshape(x,(2,-1))
print (z)

[[1 2 3]
 [4 5 6]]


In [ ]:
#borrar o añadir dimensiones
x=np.array([[1,2,3],[4,5,6]])
print(x,x.ndim,x.size,x.shape,sep='\n')

[[1 2 3]
 [4 5 6]]
2
6
(2, 3)


In [ ]:
print (np.zeros ((3,3)))
print (np.ones((3,3)))
print (np.eye((4)))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Manipulacion tensores
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print (x)
print ("x col 2 ",x[:,1])
print ("x row 3 ",x [2:])
print ("x rows 0,1 & cols 1,2:\n",x[0:2,1:3]) #https://www.adamsmith.haus/python/answers/how-to-extract-specific-columns-from-a-numpy-array-in-python

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x col 2  [ 2  6 10]
x row 3  [[ 9 10 11 12]]
x rows 0,1 & cols 1,2:
 [[2 3]
 [6 7]]


In [ ]:
#multiplicacion arrays
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8],[9,10],[11,12]])
c=a.dot(b)
print (a,b,"a x b ",c,sep='\n')
print (a.shape,".",b.shape,"=",c.shape)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
a x b 
[[ 58  64]
 [139 154]]
(2, 3) . (3, 2) = (2, 2)


In [ ]:
#Cambiar forma tensores:
x=np.array([[1,2,3,4,5,6]])
print(x,x.shape)
y=np.reshape(x,(2,3))
print (y, y.shape)


[[1 2 3 4 5 6]] (1, 6)
[[1 2 3]
 [4 5 6]] (2, 3)


In [ ]:
#Añadir/borrar dimensiones
x=np.array([[1,2,3],[4,5,6]])
print(x,x.shape)
y=np.expand_dims(x,1)
print(y,y.shape)
z=np.squeeze(y,1)
print(z,z.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[[1 2 3]]

 [[4 5 6]]] (2, 1, 3)
[[1 2 3]
 [4 5 6]] (2, 3)


In [ ]:
#Valor maximo en un tensor   Axis explained in=https://www.sharpsightlabs.com/blog/numpy-axes-explained/
x=np.array([[1,2],[3,4]])
print(np.max(x),np.argmax(x))
print(np.max(x, axis=0))

4 3
[3 4]
